export const authConstants = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAIL: "AUTH_FAIL",
  LOGOUT: "LOGOUT",
};

export const productConstants = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAIL: "ADD_PRODUCT_FAIL",
};

export const cartConstants = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",

  UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAIL: "UPDATE_CART_FAIL",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAIL: "GET_CART_FAIL",
};
